# Introduction to Data Science 2026

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [75]:
# Use this cell for your code
A = range(0, int(1e7))
B = range(0, int(1e7))

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [76]:
def add_with_for(A,B):
    C = []
    # add your code here
    for i in range(len(A)):
        C.append(A[i]+B[i])
    return C

print(add_with_for(A,B)[0:5])

[0, 2, 4, 6, 8]

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [77]:
# Use this cell for your code
import numpy as np

def add_with_numpy(A,B):
    npA = np.array(A)
    npB = np.array(B)
    return npA + npB

print(add_with_numpy(A,B)[0:5])

[0 2 4 6 8]

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [78]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
# Use this cell for your code
res = np.arange(100).reshape(10, 10)
res

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2. Create the following array:

In [80]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [81]:
# Use this cell for your code
tmp = np.array([0,1])
res = np.tile(tmp, (10, 5))
res

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

3. Create the following array (D):

In [82]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [83]:
# Use this cell for your code
arr = np.diag(np.ones(10))
D = np.ones((10, 10)) - arr 
D

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

4. Create the following array (E):

In [84]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
# Use this cell for your code
arr = np.flipud(np.diag(np.ones(10)))
E = np.ones((10, 10)) - arr

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [86]:
DE = np.matmul(D, E)
print(f"Det of D: {np.linalg.det(D)}, Det of E: {np.linalg.det(E)}, Det of DE: {np.linalg.det(DE)}")
print(f"Det(D) * Det(E) ==  Det(DE): {np.isclose(np.linalg.det(D) * np.linalg.det(E), np.linalg.det(DE))}")

Det of D: -8.999999999999998, Det of E: 9.000000000000002, Det of DE: -81.00000000000003
Det(D) * Det(E) ==  Det(DE): True

-- *Use this markdown cell for your written answer* --

This is not a coincidence: for square matrices, det(DE) = det(D) × det(E).

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [87]:
# Use this cell for your code
import sklearn
housing = sklearn.datasets.fetch_california_housing()
data = housing.data
target = housing.target
print(np.shape(data))
features = housing.feature_names
print(features)

(20640, 8)
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [88]:
# Use this cell for your code
AveBedrms = features.index('AveBedrms')
idx = np.where(data[:, AveBedrms] > 2)[0]
print(idx[0:5])
print(f"Number of rows with AveBedrms > 2: {len(idx)}")

[ 710 1023 1024 1030 1102]
Number of rows with AveBedrms > 2: 235

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [89]:
# Use this cell for your code
HouseAge = features.index('HouseAge')
idx = np.where((data[:, HouseAge] >= 1) & (data[:, HouseAge] <= 3))[0]
print(idx[0:5])
print(f"Number of rows with HouseAge between 1 and 3: {len(idx)}")

[ 59 854 871 959 976]
Number of rows with HouseAge between 1 and 3: 124

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [90]:
# Use this cell for your code
Population = features.index('Population')
idx = np.where(target[:] > 0.25)[0]
mean = np.mean(data[idx, Population])
print(f"Mean of Population: {mean}")

Mean of Population: 1425.6833737275813

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [91]:
# Use this cell for your code
import pandas as pd
path = "data/Automotive 5.json"
data = pd.read_json(path, lines=True)

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [92]:
# Use this cell for your code
reviewText = data['reviewText']
reviewText = reviewText.fillna('')
reviewText = reviewText.str.lower() 
print(reviewText[0:5])

0    after i wrote the below review, the manufactur...
1    it sucks barely picks up anything definitely n...
2    well to write a short one, it blew 2 fuses of ...
3    i have absolutely no memory of buying this but...
4                                 it ok it does it job
Name: reviewText, dtype: str

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [93]:
# Use this cell for your code
import string
stopPath = "data/stopwords.txt"
with open(stopPath, "r") as f:
    stopWords = set(f.read().split())

P = string.punctuation
trn = str.maketrans('', '', P)
clean = reviewText.apply(lambda x: ' '.join(w for w in x.translate(trn).split() if w not in stopWords))
print(clean[0:5])

0    wrote review manufacturer contacted explained ...
1    sucks barely picks definitely cars pretty dont...
2    write short blew 2 fuses car apparently demand...
3    absolutely memory buying im going review goes ...
4                                          ok does job
Name: reviewText, dtype: str

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [94]:
# Use this cell for your code
import nltk
stemmer = nltk.stem.PorterStemmer()
clean_stemmed = clean.apply(lambda x: ' '.join(stemmer.stem(w) for w in x.split()))

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [95]:
# Use this cell for your code
pos_path = "data/pos.txt"
neg_path = "data/neg.txt"

pos_idx = data['overall'] >= 4
pos = clean_stemmed[pos_idx]

neg_idx = data['overall'] <= 2
neg = clean_stemmed[neg_idx]

with open(pos_path, "w") as f:
    f.write('\n'.join(pos))

with open(neg_path, "w") as f:
    f.write('\n'.join(neg))

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**

In [50]:
import sqlite3
database_path = "data/northwind2000-simplified.sqlite"

In [52]:
conn = sqlite3.connect(database_path)
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
tables

              name
0       Categories
1  sqlite_sequence
2        Customers
3        Employees
4     OrderDetails
5           Orders
6         Products
7         Shippers
8        Suppliers

In [53]:
employees = pd.read_sql_query("SELECT * FROM Employees;", conn)
employees.head()

,EmployeeID,LastName,FirstName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,City,Region,PostalCode,Country,HomePhone,Extension,ReportsTo
0,1,Davolio,Nancy,Sales Representative,Ms.,1948-12-08,1992-05-01,507 - 20th Ave. E.Apt. 2A,Seattle,WA,98122,USA,(206) 555-9857,5467,2.0
1,2,Fuller,Andrew,"Vice President, Sales",Dr.,1952-02-19,1992-08-14,908 W. Capital Way,Tacoma,WA,98401,USA,(206) 555-9482,3457,NaN
2,3,Leverling,Janet,Sales Representative,Ms.,1963-08-30,1992-04-01,722 Moss Bay Blvd.,Kirkland,WA,98033,USA,(206) 555-3412,3355,2.0
3,4,Peacock,Margaret,Sales Representative,Mrs.,1937-09-19,1993-05-03,4110 Old Redmond Rd.,Redmond,WA,98052,USA,(206) 555-8122,5176,2.0
4,5,Buchanan,Steven,Sales Manager,Mr.,1955-03-04,1993-10-17,14 Garrett Hill,London,NaN,SW1 8JR,UK,(71) 555-4848,3453,2.0

In [73]:
res1 = pd.read_sql_query("SELECT firstName, lastName, hireDate FROM Employees WHERE hireDate > 1994-01-01;", conn)
res1

  FirstName   LastName    HireDate
0     Nancy    Davolio  1992-05-01
1    Andrew     Fuller  1992-08-14
2     Janet  Leverling  1992-04-01
3  Margaret    Peacock  1993-05-03
4    Steven   Buchanan  1993-10-17
5   Michael     Suyama  1993-10-17
6    Robert       King  1994-01-02
7     Laura   Callahan  1994-03-05
8      Anne  Dodsworth  1994-11-15

In [ ]:
orders = pd.read_sql_query("SELECT * FROM Orders;", conn)
orders.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipperID,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,3,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,1,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,2,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,1,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,2,51.30

In [60]:
products = pd.read_sql_query("SELECT * FROM Products;", conn)
products.head()

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1

In [61]:
order_details = pd.read_sql_query("SELECT * FROM OrderDetails;", conn)
order_details.head()

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10248         11       14.0        12       0.0
1    10248         42        9.8        10       0.0
2    10248         72       34.8         5       0.0
3    10249         14       18.6         9       0.0
4    10249         51       42.4        40       0.0

In [62]:
customers = pd.read_sql_query("SELECT * FROM Customers;", conn)
customers.head()

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,NaN,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,NaN,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [57]:
res2 = pd.read_sql_query("SELECT CustomerID, COUNT(OrderID) AS OrderCount FROM Orders GROUP BY CustomerID;", conn)
res2.head()

  CustomerID  OrderCount
0      ALFKI           6
1      ANATR           4
2      ANTON           7
3      AROUT          13
4      BERGS          18

In [66]:
res3 = pd.read_sql_query(
    "SELECT DISTINCT c.ContactName\
    FROM Customers c\
    JOIN Orders o ON c.CustomerID = o.CustomerID\
    JOIN OrderDetails od ON o.OrderID = od.OrderID\
    JOIN Products p ON od.ProductID = p.ProductID\
    WHERE p.ProductName = 'Chai';", conn)

res3

                ContactName
0               Horst Kloss
1              Paula Wilson
2               Fran Wilson
3               Rita Müller
4       Guillermo Fernández
5                 Yang Wang
6            Lúcia Carvalho
7            Annette Roulet
8          Isabel de Castro
9            Renate Messner
10         Pirkko Koskitalo
11     Miguel Angel Paolino
12           Jean Fresnière
13           Janine Labrune
14  Zbyszek Piestrzeniewicz
15       Frédérique Citeaux
16         Patricia McKenna
17       Christina Berglund
18           Jose Pavarotti
19         Felipe Izquierdo
20           Simon Crowther
21         Carlos Hernández
22               Hari Kumar
23            Paula Parente
24        José Pedro Freyre
25        Elizabeth Lincoln
26                 Liu Wong
27          Matti Karttunen
28            Howard Snyder
29         Pascale Cartrain
30                Ann Devon

In [69]:
res4 = pd.read_sql_query(
    "SELECT * FROM Orders\
    WHERE ShippedDate IS NULL;", conn)
res4

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipperID,Freight
0,11008,ERNSH,7,1998-04-08 00:00:00.000,1998-05-06 00:00:00.000,None,3,79.46
1,11019,RANCH,6,1998-04-13 00:00:00.000,1998-05-11 00:00:00.000,None,3,3.17
2,11039,LINOD,1,1998-04-21 00:00:00.000,1998-05-19 00:00:00.000,None,2,65.00
3,11040,GREAL,4,1998-04-22 00:00:00.000,1998-05-20 00:00:00.000,None,3,18.84
4,11045,BOTTM,6,1998-04-23 00:00:00.000,1998-05-21 00:00:00.000,None,2,70.58
5,11051,LAMAI,7,1998-04-27 00:00:00.000,1998-05-25 00:00:00.000,None,3,2.79
6,11054,CACTU,8,1998-04-28 00:00:00.000,1998-05-26 00:00:00.000,None,1,0.33
7,11058,BLAUS,9,1998-04-29 00:00:00.000,1998-05-27 00:00:00.000,None,3,31.14
8,11059,RICAR,2,1998-04-29 00:00:00.000,1998-06-10 00:00:00.000,None,2,85.80
9,11061,GREAL,4,1998-04-30 00:00:00.000,1998-06-11 00:00:00.000,None,3,14.01
10,11062,REGGC,4,1998-04-30 00:00:00.000,1998-05-28 00:00:00.000,None,2,29.93
11,11065,LILAS,8,1998-05-01 00:00:00.000,1998-05-29 00:00:00.000,None,1,12.91
12,11068,QUEEN,8,1998-05-04 00:00:00.000,1998-06-01 00:00:00.000,None,2,81.75
13,11070,LEHMS,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,None,1,136.00
14,11071,LILAS,1,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,None,1,0.93
15,11072,ERNSH,4,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,None,2,258.64
16,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,None,2,24.95
17,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,None,2,18.44
18,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,None,2,6.19
19,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,None,2,38.28
20,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,None,2,8.53

In [71]:
res5 = pd.read_sql_query(
    "SELECT c.CompanyName, COUNT(o.OrderID) AS order_count\
    FROM Customers AS c\
    JOIN Orders AS o ON c.CustomerID = o.CustomerID\
    GROUP BY c.CustomerID, c.CompanyName\
    ORDER BY order_count DESC\
    LIMIT 1;", conn)
res5

          CompanyName  order_count
0  Save-a-lot Markets           31